api/urls.py
from posixpath import basename
from accounts.views import (
    AdministratorProfileAPIView, WorkerProfileAPIView,
    VerifyMail, RequestPasswordResetEmail, SetNewPasswordAPIView,
    PasswordResetTokenCheck, LoginViewSet, RefreshViewSet, RegistrationViewSet
)
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView
from rest_framework.routers import SimpleRouter

app_name = "api"
routes = SimpleRouter()

routes.register('login', LoginViewSet, basename='login')
routes.register("signup", RegistrationViewSet,
                basename="registratiion")
routes.register('auth/refresh', RefreshViewSet,
                basename="auth_refresh")
routes.register('password-reset', RequestPasswordResetEmail,
                basename="requestPasswordReset")
routes.register('password-reset-complete', SetNewPasswordAPIView,
                basename="password-reset-complete")
#Profile
routes.register('worker/profile', WorkerProfileAPIView,
                basename="worker-profile")
routes.register("admin/profile", AdministratorProfileAPIView,
                basename="admin-profile")

urlpatterns = [
    *routes.urls,
    path('activate/', VerifyMail, name="email-verification"),
    path("password-reset/<uidb64>/<token>/",
        PasswordResetTokenCheck,
        name="password-reset-token-check"),
    path("password-reset-successful/",
        TemplateView.as_view(
            template_name="accounts/password_reset_success.html"),
        name="passwordResetSuccess"
        )
]

staff/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from rest_framework.documentation import include_docs_urls

API_TITLE = "Staff Portal"
API_DESCRIPTION = "Employees Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include_docs_urls(title=API_TITLE,
                                description=API_DESCRIPTION
                                )),
    path("api/v1/", include("api.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>Portal | {%block title%}{%endblock%}</title>
  </head>
  <body>
   {% if messages %}
         <div class="container">
         <ul class="messages p-3 list-unstyled">
             {% for message in messages %}
             <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
             {% endfor %}
         </ul>
         </div>
         {% endif %}


 
    {%block content%} {%endblock%}
   

    <!-- Optional JavaScript; choose one of the two! -->
{%block javascript%} {%endblock%}
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>

   

templates/password_reset.html
{%extends 'Accounts/base.html'%}
<!--Title-->
{%block title%}Password Reset {%endblock%}
<!--Body Content-->
{%block content%}
<div class="container mt-3">
  <div id="alert-box"></div>
  <div id="password-container">
    <div id="form-wrapper">
      <form id="form">
        <div class="mb-3">
          <label for="password1" class="form-label">Password</label>
          <input type="password" required class="form-control" id="password1" />
        </div>
        <div class="mb-3">
          <label for="password2" class="form-label"
            >Password Confirmation</label
          >
          <input type="password" required class="form-control" id="password2" />
        </diimport osv>
        <button type="submit" id="submit" class="btn btn-outline-primary">
          Reset
        </button>
      </form>
    </div>
  </div>
</div>

{%endblock%}
<!--JavaScript-->
{%block javascript%}
<script type="text/javascript">
  var form = document.getElementById("form-wrapper");

  form.addEventListener("submit", function (e) {
    e.preventDefault();
    console.log("Form submitted");
    password1 = document.getElementById("password1").value;
    console.log(password1);
    password2 = document.getElementById("password2").value;
    uidb64 = "{{uidb64}        }";
    token = "{{token}}";
    var url = "{%url 'api:password-reset-complete-list'%}";
    fetch(url, {
      method: "POST",
      body: JSON.stringify({
        password: password1,
        password_confirmation: password2,
        uidb64: uidb64,
        token: token,
      }),
      headers: {
        "Content-Type": "application/json",
        csrfmiddlewaretoken: "{{csrf_token}}",
      },
    })
      .then((response) => response.json())
      .then(function (data) {
        if (data["success"]) {
          handleAlerts("success", data["success"]);
          location.href = "{%url 'api:passwordResetSuccess'%}";
        } else {
          handleAlerts("warning", data["detail"]);
        }
      });
  });
  // Alert Handlers
  var alertBox = document.getElementById("alert-box");
  var handleAlerts = (type, msg) => {
    alertBox.innerHTML = `
      <div class="alert alert-${type}" role="alert">
      ${msg}
        </div>`;
    setTimeout(function () {
      alertBox.remove();
    }, 5000);
  };
</script>
{%endblock%}

templates/password_reset_success.html
{%extends 'accounts/base.html'%}
<!---->
{%block title%} Password Reset Success {%endblock%}
<!---->
{%block content%}
<div class="container mt-2">
  <div class="alert alert-success" role="alert">
    Password Reset was Successful
  </div>
</div>
{%endblock%}
<!---->
{%block javascript%} {%endblock%}

templates/verify.html
{%extends 'accounts/base.html'%}
<!--Title-->
{%block title%} Account Verification {%endblock%}
<!--Body Content-->
{%block content%} {%endblock%}
<!--JavaScript-->
{%block javascript%} {%endblock%}